### ISSUE TITLE
Add support for 3d graphics

### ISSUE THREAD

**Issue by S-B99** [lispysnake/serpent#4]
← Arrows to the left

**Comment by ikeycode** [comment]
So - the idea is an abstract pipeline implementation that just leverages bgfx. We'll provide utility classes and methods for all the useful stuff, and a default 2d pipeline. There's no *reason* why you couldn't add 3D on top, its a very light framework as opposed to a full-fat engine (we believe most of the logic will live in your game, anyway.)

For now our priorities will be 2D (on 3D pipeline) but we'll create the project in a way it could potentially be extended in future.

**Comment by p0nce** [comment]
Hello. (author of `gfm` and various D libs).

Very interesting project! Very cool that you are supporting D and I very mich agree with building upon bgfx.

I'm a recent user of Godot engine and some things have strike me in that engine:
- first of all, Godot uses OpenGL directly which is a trap imho
- Godot's `Transform` is very good with readable names, however it has no "shearing", or perspective deformation allowed. When `Transform` is converted to a row-major 4x4 matrix, the last line is forced to be `[0, 0, 0, 1]`. Though maybe understandability wins.
- Godot duplicate a lot of functionality between 2D and 3D (navmeshes, pathfinding, etc.), despite 2D being mostly a subset of 3D. I agree 2D is easier to author and even make an engine for, but I think supporting 3D "only" still allows 2D games.

**Comment by ikeycode** [comment]
So I'd initially class this as implemented in terms of project *direction*.

Whilst we lack almost all major functionalities, the architecture is starting to shape up to be something that transparently handles 3D or 2D. For now we have basic `Entity` type which at minimum stores some positions. We'll extend them through tagging, and for example, have a `SpriteRenderer` looking for texture information. Theoretically we could support a `MeshRenderer` with the same tagging system and support a data driven entity design.
